### ISSUE TITLE
Scanner glitches in Android-Chrome

### ISSUE THREAD

**Issue by searleser97** [mebjas/html5-qrcode#664]
**Describe the bug**
The scanner is not rendering the camera view properly in Chrome on Android, it glitches the half of the camera view.

This bug only happens on Android-Chrome in the latest versions, I tested in iOS (chrome and safari) and it works correctly, also using "Brave Browser" in Android works perfectly as well.

https://user-images.githubusercontent.com/5056411/210830985-7ce8473f-0928-493b-b6ca-765bbee24c1c.mov
```js
    html5Qrcode.start(
      { facingMode: "environment" },
      {
        fps: 10,
        qrbox: qrBoxSize,
        aspectRatio,
      },
      onScanSuccess,
      onScanFailure
    );
```

```html
  <div id="reader" />
```
##### CSS
```css
  #reader {
    width: 100%;
    aspect-ratio: 16/9;
    background-color: black;
  }
```
